//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This source code was auto-generated by xsd, Version=4.6.1055.0.

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class calendars
{
    private string calendarField;
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string calendar
    {
        get
        {
            return this.calendarField;
        }
        set
        {
            this.calendarField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class curvepoint
{
    private string tenorField;
    private string maturitydateField;
    // private string parrateField;
    private double parrateField;
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string tenor
    {
        get
        {
            return this.tenorField;
        }
        set
        {
            this.tenorField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string maturitydate
    {
        get
        {
            return this.maturitydateField;
        }
        set
        {
            this.maturitydateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double parrate
    {
        get
        {
            return this.parrateField;
        }
        set
        {
            this.parrateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class interestRateCurve
{
    private string effectiveasofField;
    private string currencyField;
    private string baddayconventionField;
    private interestRateCurveDeposits[] depositsField;
    private interestRateCurveSwaps[] swapsField;
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string effectiveasof
    {
        get
        {
            return this.effectiveasofField;
        }
        set
        {
            this.effectiveasofField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string baddayconvention
    {
        get
        {
            return this.baddayconventionField;
        }
        set
        {
            this.baddayconventionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("deposits", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public interestRateCurveDeposits[] deposits
    {
        get
        {
            return this.depositsField;
        }
        set
        {
            this.depositsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("swaps", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public interestRateCurveSwaps[] swaps
    {
        get
        {
            return this.swapsField;
        }
        set
        {
            this.swapsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class interestRateCurveDeposits
{
    private string daycountconventionField;
    private string snaptimeField;
    private string spotdateField;
    private calendars[] calendarsField;
    private curvepoint[] curvepointField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string daycountconvention
    {
        get
        {
            return this.daycountconventionField;
        }
        set
        {
            this.daycountconventionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string snaptime
    {
        get
        {
            return this.snaptimeField;
        }
        set
        {
            this.snaptimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spotdate
    {
        get
        {
            return this.spotdateField;
        }
        set
        {
            this.spotdateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("calendars")]
    public calendars[] calendars
    {
        get
        {
            return this.calendarsField;
        }
        set
        {
            this.calendarsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("curvepoint")]
    public curvepoint[] curvepoint
    {
        get
        {
            return this.curvepointField;
        }
        set
        {
            this.curvepointField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class interestRateCurveSwaps
{
    private string fixeddaycountconventionField;
    private string floatingdaycountconventionField;
    private string fixedpaymentfrequencyField;
    private string floatingpaymentfrequencyField;
    private string snaptimeField;
    private string spotdateField;
    private calendars[] calendarsField;
    private curvepoint[] curvepointField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fixeddaycountconvention
    {
        get
        {
            return this.fixeddaycountconventionField;
        }
        set
        {
            this.fixeddaycountconventionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string floatingdaycountconvention
    {
        get
        {
            return this.floatingdaycountconventionField;
        }
        set
        {
            this.floatingdaycountconventionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fixedpaymentfrequency
    {
        get
        {
            return this.fixedpaymentfrequencyField;
        }
        set
        {
            this.fixedpaymentfrequencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string floatingpaymentfrequency
    {
        get
        {
            return this.floatingpaymentfrequencyField;
        }
        set
        {
            this.floatingpaymentfrequencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string snaptime
    {
        get
        {
            return this.snaptimeField;
        }
        set
        {
            this.snaptimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spotdate
    {
        get
        {
            return this.spotdateField;
        }
        set
        {
            this.spotdateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("calendars")]
    public calendars[] calendars
    {
        get
        {
            return this.calendarsField;
        }
        set
        {
            this.calendarsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("curvepoint")]
    public curvepoint[] curvepoint
    {
        get
        {
            return this.curvepointField;
        }
        set
        {
            this.curvepointField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private object[] itemsField;
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("calendars", typeof(calendars))]
    [System.Xml.Serialization.XmlElementAttribute("curvepoint", typeof(curvepoint))]
    [System.Xml.Serialization.XmlElementAttribute("interestRateCurve", typeof(interestRateCurve))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

